# -*- coding: utf-8 -*-
"""Data Cleaning & Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGX_pxC6n6bQrjETvllEK3PB7aV6Dgv2
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import os

from sklearn.preprocessing import LabelEncoder, StandardScaler

# ============================================
# 1. Download and Load Dataset
# ============================================

print("Downloading dataset...")

path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Dataset downloaded to:")
print(path)

print("\nFiles in dataset folder:")
print(os.listdir(path))

# Load CSV file
csv_path = os.path.join(path, "Titanic-Dataset.csv")
df = pd.read_csv(csv_path)

# ============================================
# 2. Explore Dataset
# ============================================

print("\nFirst 5 Rows")
print(df.head())

print("\nDataset Shape")
print(df.shape)

print("\nDataset Information")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nStatistical Summary")
print(df.describe())

plt.figure(figsize=(8,5))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values")
plt.savefig("missing_values.png", dpi=300, bbox_inches="tight")
plt.show()

# ============================================
# 3. Handle Missing Values
# ============================================

# Fill missing Age values with median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Embarked values with mode
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Drop Cabin because it has many missing values
df.drop("Cabin", axis=1, inplace=True)

print("\nMissing Values After Cleaning")
print(df.isnull().sum())

# ============================================
# 4. Encode Categorical Variables
# ============================================

encoder = LabelEncoder()

df["Sex"] = encoder.fit_transform(df["Sex"])
df["Embarked"] = encoder.fit_transform(df["Embarked"])

print("\nEncoded Columns Successfully.")

# ============================================
# 5. Remove Unnecessary Columns
# ============================================

columns_to_drop = ["PassengerId", "Name", "Ticket"]

for col in columns_to_drop:
    if col in df.columns:
        df.drop(col, axis=1, inplace=True)

print("\nRemaining Columns")
print(df.columns)

# ============================================
# 6. Standardize Numerical Features
# ============================================

scaler = StandardScaler()

numeric_columns = ["Age", "Fare"]

df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

print("\nFeature Scaling Completed.")

# ============================================
# 7. Visualize Outliers
# ============================================

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
sns.boxplot(y=df["Age"])
plt.title("Age Boxplot")


plt.tight_layout()
plt.show()

plt.figure(figsize=(10,4))

plt.subplot(1,2,2)
sns.boxplot(y=df["Fare"])
plt.title("Fare Boxplot")

plt.tight_layout()
plt.show()

# ============================================
# 8. Remove Outliers using IQR (Fare)
# ============================================

Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df["Fare"] >= lower) & (df["Fare"] <= upper)]

print("\nShape After Removing Outliers")
print(df.shape)

# ============================================
# 9. Save Cleaned Dataset
# ============================================

df.to_csv("Titanic_Cleaned.csv", index=False)

print("\nCleaned dataset saved as Titanic_Cleaned.csv")

# ============================================
# 10. Final Preview
# ============================================

print("\nFinal Dataset")
print(df.head())

print("\nFinal Dataset Info")
print(df.info())

print("\nPreprocessing Completed Successfully!")

plt.figure(figsize=(10,6))
plt.axis('off')
plt.text(0.01, 0.99, str(df.info()), fontsize=10, va='top')
plt.savefig("dataset_info.png", dpi=300, bbox_inches="tight")
plt.close()

# ============================================
# Save Cleaned Dataset
# ============================================

output_file = "Titanic_Cleaned.csv"
df.to_csv(output_file, index=False)

print(f"\nCleaned dataset saved successfully as '{output_file}'")

